# Generated by Django 3.0.3 on 2020-12-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('anel', 'Anel'), ('bolsa', 'Bolsa'), ('bijuterias', 'Bijuterias'), ('brincos', 'Brincos')], default='brincos', max_length=100),
            preserve_default=False,
        ),
    ]
