# Generated by Django 2.2.13 on 2020-12-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is where the text description will come.'),
            preserve_default=False,
        ),
    ]
